### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by necolas** [h5bp/server-configs-node#11]
The name "h5bp" is vague and it feels confusing to have a server config package named after a software organization. I'd suggest that an alternative name (that's clearer) is used at some point in the future.

**Comment by ngryman** [comment]
@arthurvr What do you think about this one? Should we? Or leave it.

**Comment by arthurvr** [comment]
We should change it IMHO.

**Comment by ngryman** [comment]
Let's go for `h5bp-server` ?

**Comment by arthurvr** [comment]
I think that's okay. Other options could be `server-configs-node`, or `h5bp-server-configs`. Not sure but I would prefer it to be consistent with `apache-server-configs`.

**Comment by ngryman** [comment]
So let's go for `h5bp-server`?

IMHO:
 - no need to mention `node` in the name as it's on `npm`.
 - it's not a *config* but a server, so `configs` in the name seems weird.
 - mentioning `h5bp` is important as there is no context on `npm`.

Checklist:
 - [ ] rename the repo.
 - [ ] open PR for other projects mentioning it.
 - [ ] unpublish `h5bp`.
 - [ ] publish `h5bp-server`.

Also, I think I'm gonna sync it with:
 - [ ] Bumping version to `1.0.0`.
 - [ ] Merging the `bump-deps` branch.
