### ISSUE TITLE
Do we need `cache.js` in the repo?

### ISSUE THREAD

**Issue by arthurvr** [h5bp/server-configs-node#54]
It's third party code so let's see how we can pull it in using npm.

Or even better, search another solution as the `cache.js` code dates from 2011.

**Comment by ngryman** [comment]
Ok.

I have the feeling that you guys would like to drop features like dynamic stylesheet and javascript processing. If so, cache would be deprecated.

**Comment by arthurvr** [comment]
> I have the feeling that you guys would like to drop features like dynamic stylesheet and javascript processing. If so, cache would be deprecated

I never said to drop them but at least I think they should be distributed as separated modules. IMHO at least.

**Comment by ngryman** [comment]
I agree, what do you think about #55?
