### ISSUE TITLE
v1.0.0 roadmap

### ISSUE THREAD

**Issue by ngryman** [h5bp/server-configs-node#55]
Hi guys,

`server-configs-node` is aging and offers features like style and javascript processing that may be out of scope. I would like to propose a full clean rewrite that only reflects other server configs.

This project is a little different than other `server-configs-*` projects since it's a server. But the community is already using existing libraries like `express` to create servers. So I think we should only propose a _universal_ middleware that would work in any context, instead of a server.
We could officially support most used libraries by default (`express`, `builtin`, others?).

This rewrite would aim the `1.0.0` release and freeze the api to a single function taking options (like any middleware). A migration guide would be provided for users that want to upgrade and keep existing style and javascript processing.
The current _legacy_ version would be supported in a separated branch.

@h5bp/owners @h5bp/server-configs What do you think? Do you have any feedback on this?

Thanks!

**Comment by EzraLopez** [comment]
Hey @ngryman!
I came here for Google's recommendation: https://developers.google.com/speed/docs/insights/EnableCompression

Is this middleware still good to use? I see the dependency status is insecure and the devDependency status is out of date.

**Comment by ngryman** [comment]
Hey,

TBH this repo has not been maintained for a while. There are a bunch of middlewares out there that could fulfill your needs. For example, if you need compression: https://github.com/expressjs/compression.

**Comment by EzraLopez** [comment]
Thanks @ngryman!

**Comment by xonecas** [comment]
@ngryman You've been the most active in this repo, and while I would love to spend time refactoring this project, my current professional situation is too time consuming. I say that if you have the time, the changes you proposed are great.
